### ISSUE TITLE
Not getting any annotation outputted in build

### ISSUE THREAD

**Issue by acetinick** [ticky/simplecov-buildkite#13]
hi,

I have followed the steps and running the build using buildkite, however not getting an annotation displayed.

This is what I have in my test_helper.rb

`ENV["RAILS_ENV"] ||= "test"

require "simplecov"
require "simplecov-buildkite"

SimpleCov.start "rails" do
  load_profile "buildkite"

  add_filter "/bin/"
  add_filter "/db/"
  add_filter "/spec/" # for rspec
  add_filter "/test/" # for minitest

  formatter SimpleCov::Formatter::MultiFormatter.new(
    [
      SimpleCov::Formatter::HTMLFormatter,
      SimpleCov::Buildkite::AnnotationFormatter,
    ])
end`

This is what is outputted from my test step

![image](https://user-images.githubusercontent.com/571649/102008389-9c9e1200-3d38-11eb-88f9-1bc8731e495f.png)

**Comment by acetinick** [comment]
Strange,  I also see this at the top when tests start

![image](https://user-images.githubusercontent.com/571649/102008805-dfadb480-3d3b-11eb-82e8-231a1090ada5.png)

**Comment by ticky** [comment]
Hi @acetinick, I’m doing my best to not look at work-related things for the holidays, so please forgive me for giving quick direction rather than pushing commits here 🙇🏻‍♀️

The gem relies on [seeing the environment variable `BUILDKITE`](https://github.com/ticky/simplecov-buildkite/blob/2a1b43b19d9157b3ac03e5291c65ace0c6dd254a/lib/simplecov/buildkite/annotation_formatter.rb#L55) to determine whether to try posting the status. From a quick glance at the screenshots you seem to be using Docker, say guess is need to expose that variable to the running container.

**Comment by abury** [comment]
@acetinick how did you end up going with this one? We're also running this from within docker and can't seem to get it to work.

**Comment by aleksclark** [comment]
@abury Looking at the source the following env vars need to be forwarded into docker:

```yaml
  - label: ":rspec: Rspec"
    if: build.message !~ /\[skip tests\]/i
    key: "rspec"
    depends_on: "docker-push-test"
    parallelism: 8
    command: docker/ruby_specs.sh
    plugins:
      - docker-compose#v4.8.0:
          run: my_app
          graceful-shutdown: true
          image-repository: ${ECR_REPO}
          image-name: test-${BUILDKITE_BRANCH}-${BUILDKITE_BUILD_NUMBER}
          use-aliases: true
          env:
            - BUILDKITE
            - BUILDKITE_BRANCH
            - BUILDKITE_PULL_REQUEST_BASE_BRANCH
            - BUILDKITE_PIPELINE_DEFAULT_BRANCH
            - BUILDKITE_COMMIT
   ```
